# 1. workflow的名字, 可以不做修改
name: Docker Image CI on BJ-DS1

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Hangzhou18
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Generate image tag
      id: vars
      run: |
        echo "IMAGE_TAG=$(date +'%Y%m%d-%H%M%S')-$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_ENV
        echo $IMAGE_TAG

    - name: Login to Docker Registry
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login crhz.ai4x.com.cn -u ${{ vars.DOCKER_USER }} --password-stdin

    - name: Build and push image
      env:
        APP_NAME: cosyvoice
      run: |
        docker build -f ./runtime/python/Dockerfile -t crhz.ai4x.com.cn/$APP_NAME:$IMAGE_TAG .
        docker push crhz.ai4x.com.cn/$APP_NAME:$IMAGE_TAG
        echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
